import { User, Team, Chat, CalendarMeeting, FileItem, ThreadReply } from './types';

export const CURRENT_USER: User = {
  id: 'user-current',
  name: 'Alex Rivera',
  avatar: 'AR',
  role: 'Principal UX Engineer',
  status: 'online',
  email: 'alex.rivera@enterprise.com',
  customStatus: 'Coding a high-fidelity Teams clone 🚀',
};

export const USERS: User[] = [
  CURRENT_USER,
  {
    id: 'user-1',
    name: 'Sarah Chen',
    avatar: 'SC',
    role: 'Lead Frontend Architect',
    status: 'busy',
    email: 'sarah.chen@enterprise.com',
    customStatus: 'In a meeting • Do not disturb',
  },
  {
    id: 'user-2',
    name: 'Marcus Vance',
    avatar: 'MV',
    role: 'Staff Product Designer',
    status: 'online',
    email: 'marcus.vance@enterprise.com',
    customStatus: 'Polishing layout spacing ✨',
  },
  {
    id: 'user-3',
    name: 'Emily Zhao',
    avatar: 'EZ',
    role: 'Director of Product',
    status: 'away',
    email: 'emily.zhao@enterprise.com',
    customStatus: 'Be right back',
  },
  {
    id: 'user-4',
    name: 'David Kim',
    avatar: 'DK',
    role: 'Principal DevOps Architect',
    status: 'offline',
    email: 'david.kim@enterprise.com',
  },
  {
    id: 'user-5',
    name: 'Sophia Patel',
    avatar: 'SP',
    role: 'Senior Technical Writer',
    status: 'online',
    email: 'sophia.patel@enterprise.com',
  },
];

export const MOCK_TEAMS: Team[] = [
  {
    id: 'team-1',
    name: 'Apollo Design System',
    avatar: 'AD',
    membersCount: 14,
    channels: [
      {
        id: 'c-apollo-gen',
        name: 'General',
        description: 'Global announcements and general discussions for the Apollo Design System.',
        isPrivate: false,
        unreadCount: 0,
        messages: [
          {
            id: 'm-apollo-gen-1',
            senderId: 'user-3',
            senderName: 'Emily Zhao',
            senderAvatar: 'EZ',
            content: 'Welcome everyone to the Apollo Design System v2.0 kick-off! We are standardizing all enterprise design foundations this half.',
            timestamp: '2026-07-06T09:30:00Z',
            reactions: [
              { emoji: '🎉', count: 6, users: ['user-1', 'user-2', 'user-current', 'user-4'] },
              { emoji: '🚀', count: 4, users: ['user-1', 'user-current'] },
            ],
            replyCount: 2,
          },
          {
            id: 'm-apollo-gen-2',
            senderId: 'user-2',
            senderName: 'Marcus Vance',
            senderAvatar: 'MV',
            content: 'I have updated the Figma file with the updated layout tokens. Please check out the #Tokens & Themes channel for the detailed specification!',
            timestamp: '2026-07-06T10:15:00Z',
            reactions: [
              { emoji: '👍', count: 3, users: ['user-1', 'user-current'] },
            ],
          },
        ],
      },
      {
        id: 'c-apollo-components',
        name: 'Component Library',
        description: 'React, Figma, and HTML code implementations of the Apollo component library.',
        isPrivate: false,
        unreadCount: 2,
        messages: [
          {
            id: 'm-apollo-comp-1',
            senderId: 'user-1',
            senderName: 'Sarah Chen',
            senderAvatar: 'SC',
            content: 'Did anyone face performance bottlenecks with the virtualized grid scroll inside nested tables? I am refactoring this today.',
            timestamp: '2026-07-06T11:05:00Z',
            reactions: [
              { emoji: '👀', count: 2, users: ['user-current', 'user-2'] },
            ],
            replyCount: 3,
          },
          {
            id: 'm-apollo-comp-2',
            senderId: 'user-current',
            senderName: 'Alex Rivera',
            senderAvatar: 'AR',
            content: 'Yes! The layout recalculations were firing too frequently. Debouncing the ResizeObserver callback in the wrapper fixed it on my branch. I can push a PR.',
            timestamp: '2026-07-06T11:42:00Z',
            reactions: [
              { emoji: '🔥', count: 4, users: ['user-1', 'user-2', 'user-3'] },
            ],
            attachments: [
              { id: 'att-1', name: 'grid-perf-fix.ts', type: 'code', size: '12.4 KB' },
            ],
          },
        ],
      },
      {
        id: 'c-apollo-tokens',
        name: 'Tokens & Themes',
        description: 'Global design systems values, spacing systems, semantic color maps, and theming guidelines.',
        isPrivate: false,
        unreadCount: 0,
        messages: [
          {
            id: 'm-apollo-tok-1',
            senderId: 'user-2',
            senderName: 'Marcus Vance',
            senderAvatar: 'MV',
            content: 'Here is the JSON file for our core semantic layout tokens. This governs all layouts, grids, margins, and borders under our strict Dark Mode design specification.',
            timestamp: '2026-07-06T10:30:00Z',
            reactions: [
              { emoji: '💖', count: 3, users: ['user-1', 'user-current'] },
            ],
            attachments: [
              { id: 'att-2', name: 'apollo-tokens-v2.json', type: 'json', size: '4.8 KB' },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 'team-2',
    name: 'Teams Core Platform',
    avatar: 'TC',
    membersCount: 28,
    channels: [
      {
        id: 'c-core-gen',
        name: 'General',
        description: 'Core platform discussions, releases, and architecture plans.',
        isPrivate: false,
        unreadCount: 0,
        messages: [
          {
            id: 'm-core-gen-1',
            senderId: 'user-4',
            senderName: 'David Kim',
            senderAvatar: 'DK',
            content: 'Production servers were successfully migrated to the new isolated multi-region containers. Average connection latencies have dropped by 180ms worldwide!',
            timestamp: '2026-07-06T08:00:00Z',
            reactions: [
              { emoji: '🚀', count: 12, users: ['user-1', 'user-current', 'user-2', 'user-3'] },
              { emoji: '🙌', count: 8, users: ['user-2', 'user-3'] },
            ],
          },
        ],
      },
      {
        id: 'c-core-perf',
        name: 'Performance',
        description: 'Profiling memory usage, frame pacing, bundle optimizations, and hydration speeds.',
        isPrivate: false,
        unreadCount: 1,
        messages: [
          {
            id: 'm-core-perf-1',
            senderId: 'user-1',
            senderName: 'Sarah Chen',
            senderAvatar: 'SC',
            content: 'We need to lazy-initialize all third-party SDKs to prevent blockage during startup. Currently, bundle size is 1.4MB, targeting 600KB.',
            timestamp: '2026-07-06T14:15:00Z',
            reactions: [
              { emoji: '🎯', count: 2, users: ['user-current', 'user-4'] },
            ],
          },
        ],
      },
    ],
  },
];

export const MOCK_CHATS: Chat[] = [
  {
    id: 'chat-1',
    name: 'Sarah Chen',
    type: 'direct',
    participants: [USERS[0], USERS[1]],
    unreadCount: 1,
    messages: [
      {
        id: 'm-chat-1-1',
        senderId: 'user-current',
        senderName: 'Alex Rivera',
        senderAvatar: 'AR',
        content: 'Hey Sarah, are we still on for reviewing the grid performance layout refactor at 2:00 PM?',
        timestamp: '2026-07-06T13:45:00Z',
        reactions: [],
      },
      {
        id: 'm-chat-1-2',
        senderId: 'user-1',
        senderName: 'Sarah Chen',
        senderAvatar: 'SC',
        content: 'Hey Alex! Yes, absolutely. I am looking over the branch right now. It looks very clean. Let us use the video call to go over the edge cases.',
        timestamp: '2026-07-06T13:48:00Z',
        reactions: [
          { emoji: '👍', count: 1, users: ['user-current'] },
        ],
      },
    ],
  },
  {
    id: 'chat-2',
    name: 'Marcus Vance',
    type: 'direct',
    participants: [USERS[0], USERS[2]],
    unreadCount: 0,
    messages: [
      {
        id: 'm-chat-2-1',
        senderId: 'user-2',
        senderName: 'Marcus Vance',
        senderAvatar: 'MV',
        content: 'Hey Alex! Did you check out the dark theme palette tokens? Is `bg-[#0B0F19]` rich enough or should we darken the canvas to pure solid black `#020617`?',
        timestamp: '2026-07-06T11:20:00Z',
        reactions: [],
      },
      {
        id: 'm-chat-2-2',
        senderId: 'user-current',
        senderName: 'Alex Rivera',
        senderAvatar: 'AR',
        content: 'I think `bg-[#0B0F19]` is gorgeous. Pure black can create high-contrast eye strain, whereas this deep midnight dark blue has an extremely premium, high-fidelity engineering feel.',
        timestamp: '2026-07-06T11:24:00Z',
        reactions: [
          { emoji: '🔥', count: 1, users: ['user-2'] },
        ],
      },
      {
        id: 'm-chat-2-3',
        senderId: 'user-2',
        senderName: 'Marcus Vance',
        senderAvatar: 'MV',
        content: 'Agreed! Let us run with that. Standard UI cards will use `bg-[#111827]`. It creates perfect visual hierarchy.',
        timestamp: '2026-07-06T11:25:00Z',
        reactions: [
          { emoji: '🙌', count: 1, users: ['user-current'] },
        ],
      },
    ],
  },
  {
    id: 'chat-3',
    name: 'Frontend Architecture Guild',
    type: 'group',
    participants: [USERS[0], USERS[1], USERS[4]],
    unreadCount: 3,
    messages: [
      {
        id: 'm-chat-3-1',
        senderId: 'user-4',
        senderName: 'David Kim',
        senderAvatar: 'DK',
        content: 'I have set up the Docker templates for the dev servers. HMR is disabled in development inside containers, so make sure to check the dev logs if something hangs.',
        timestamp: '2026-07-06T07:15:00Z',
        reactions: [],
      },
      {
        id: 'm-chat-3-2',
        senderId: 'user-1',
        senderName: 'Sarah Chen',
        senderAvatar: 'SC',
        content: 'Awesome! That matches our custom Vite config. This will stop random browser flickering while typing code.',
        timestamp: '2026-07-06T07:30:00Z',
        reactions: [
          { emoji: '💖', count: 2, users: ['user-4', 'user-current'] },
        ],
      },
    ],
  },
];

export const MOCK_THREAD_REPLIES: ThreadReply[] = [
  {
    id: 'tr-1',
    messageId: 'm-apollo-gen-1',
    senderId: 'user-1',
    senderName: 'Sarah Chen',
    senderAvatar: 'SC',
    content: 'Awesome! Ready to dive in. Is there an official board for design tokens feedback?',
    timestamp: '2026-07-06T09:35:00Z',
    reactions: [
      { emoji: '👍', count: 2, users: ['user-2', 'user-current'] },
    ],
  },
  {
    id: 'tr-2',
    messageId: 'm-apollo-gen-1',
    senderId: 'user-2',
    senderName: 'Marcus Vance',
    senderAvatar: 'MV',
    content: 'Yes! We are using #Tokens & Themes for all visual variables and semantic layout details.',
    timestamp: '2026-07-06T09:40:00Z',
    reactions: [],
  },
  {
    id: 'tr-3',
    messageId: 'm-apollo-comp-1',
    senderId: 'user-current',
    senderName: 'Alex Rivera',
    senderAvatar: 'AR',
    content: 'Yes, I noticed it scrolling smoothly on Chrome but lagging slightly in Firefox. I am profiling it right now.',
    timestamp: '2026-07-06T11:12:00Z',
    reactions: [
      { emoji: '👍', count: 1, users: ['user-1'] },
    ],
  },
  {
    id: 'tr-4',
    messageId: 'm-apollo-comp-1',
    senderId: 'user-2',
    senderName: 'Marcus Vance',
    senderAvatar: 'MV',
    content: 'I noticed that too. Keep us updated on what you find! I suspect nested DOM nodes are causing layout thrashing.',
    timestamp: '2026-07-06T11:15:00Z',
    reactions: [],
  },
];

export const MOCK_MEETINGS: CalendarMeeting[] = [
  {
    id: 'meet-1',
    title: 'H1 Product Strategy Alignment',
    organizer: 'Emily Zhao',
    date: '2026-07-06',
    startTime: '09:00',
    endTime: '09:45',
    description: 'Quarterly review of our main strategic themes, OKRs, and pipeline prioritization across teams.',
    attendees: ['Emily Zhao', 'Sarah Chen', 'Marcus Vance', 'Alex Rivera'],
  },
  {
    id: 'meet-2',
    title: 'Daily Standup Sync',
    organizer: 'Sarah Chen',
    date: '2026-07-06',
    startTime: '10:00',
    endTime: '10:20',
    description: 'Quick check-in on yesterday achievements, blockages, and tasks planned for today.',
    attendees: ['Sarah Chen', 'Marcus Vance', 'Alex Rivera', 'David Kim'],
    isLive: true,
  },
  {
    id: 'meet-3',
    title: 'Apollo Component Library Review',
    organizer: 'Alex Rivera',
    date: '2026-07-06',
    startTime: '14:00',
    endTime: '15:00',
    description: 'Detailed code and UX walkthrough of virtualized table scrolling and flexible column widths.',
    attendees: ['Alex Rivera', 'Sarah Chen', 'Marcus Vance'],
  },
  {
    id: 'meet-4',
    title: 'Weekly DevOps Board Sync',
    organizer: 'David Kim',
    date: '2026-07-07',
    startTime: '11:00',
    endTime: '11:30',
    description: 'Reviewing pipeline performance, cluster scaling indices, and edge network delivery.',
    attendees: ['David Kim', 'Sarah Chen', 'Alex Rivera'],
  },
];

export const MOCK_FILES: FileItem[] = [
  {
    id: 'f-1',
    name: 'apollo-design-spec-v2.pdf',
    type: 'pdf',
    size: '8.4 MB',
    uploadedBy: 'Marcus Vance',
    uploadedAt: '2026-07-05T16:40:00Z',
    teamId: 'team-1',
    channelId: 'c-apollo-gen',
  },
  {
    id: 'f-2',
    name: 'apollo-tokens-v2.json',
    type: 'code',
    size: '4.8 KB',
    uploadedBy: 'Marcus Vance',
    uploadedAt: '2026-07-06T10:30:00Z',
    teamId: 'team-1',
    channelId: 'c-apollo-tokens',
  },
  {
    id: 'f-3',
    name: 'frontend-metrics-q2.xlsx',
    type: 'xls',
    size: '1.2 MB',
    uploadedBy: 'Sarah Chen',
    uploadedAt: '2026-07-04T09:12:00Z',
    teamId: 'team-2',
    channelId: 'c-core-perf',
  },
  {
    id: 'f-4',
    name: 'docker-compose-production.zip',
    type: 'zip',
    size: '412 KB',
    uploadedBy: 'David Kim',
    uploadedAt: '2026-07-03T11:00:00Z',
  },
  {
    id: 'f-5',
    name: 'architecture-whitepaper.docx',
    type: 'doc',
    size: '2.1 MB',
    uploadedBy: 'Sophia Patel',
    uploadedAt: '2026-07-02T15:30:00Z',
  },
];
